apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluentd-ds
  labels: 
    k8s-app: fluentd-logging
    version: v1
spec:
  selector:
    matchLabels:
      name: fluentd-ds
  template:
    metadata:
      labels:
        name: fluentd-ds
        k8s-app: fluentd-logging
        version: v1
    spec:
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      terminationGracePeriodSeconds: 30
      containers:
      - name: fluentd-ds
        image: fluent/fluentd:v1.9-1
        resources:
          limits:
            memory: 200Mi
        env:
          - name: FLUENTD_CONF
            value: "fluentd-kube.conf"
        volumeMounts:
        - name: fluentd-conf
          mountPath: /fluentd/etc
      volumes:
      - name: fluentd-conf
        configMap:
          name: fluentd-config