secretGenerator:
  - name: postgres-pw
    literals:
    - password=transactions_pw
resources:
  - postgres-deployment.yaml
  - transaction-pool-deployment.yaml
  - transaction-spawner-cronjob.yaml
  - ./monitoring/grafana-config-configmap.yaml
  - ./monitoring/grafana-deployment.yaml
  - ./fluent/fluentd-config-configmap.yaml