apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    app: dummy-blockchain
spec:
  ports:
    - port: 5432
  selector:
    app: dummy-blockchain
    tier: postgres
  clusterIP: None
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  labels:
    app: dummy-blockchain
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  labels:
    app: dummy-blockchain
spec:
  selector:
    matchLabels:
      app: dummy-blockchain
      tier: postgres
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: dummy-blockchain
        tier: postgres
    spec:
      containers:
      - image: postgres:13.2-alpine
        name: postgres
        env:
        - name: POSTGRES_DB
          value: transactions_db
        - name: POSTGRES_USER
          value: transactions_user
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-pw
              key: password
        ports:
        - containerPort: 5432
          name: postgres
        volumeMounts:
        - name: postgres-persistent-storage
          mountPath: /var/lib/postgres
      volumes:
      - name: postgres-persistent-storage
        persistentVolumeClaim:
          claimName: postgres-pvc