apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: transaction-spawner
  labels:
    app: blockchain-demo
    component: transaction-spawner
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: transaction-spawner
            image: philohsophy/transaction-spawner:0.0.1
            imagePullPolicy: IfNotPresent
            env:
            - name: TRANSACTION_POOL_BASE_URL
              value: http://transaction-pool
          restartPolicy: OnFailure