---
apiVersion: v1
kind: Service
metadata:
  name: transaction-pool
  labels:
    app: dummy-blockchain
spec:
  selector:
    app: dummy-blockchain
    component: transaction-pool
  ports:
    - port: 80
      targetPort: http-pool
      protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: transaction-pool
  labels:
    app: dummy-blockchain
spec:
  selector:
    matchLabels:
      app: dummy-blockchain
      component: transaction-pool
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: dummy-blockchain
        component: transaction-pool
    spec:
      containers:
      - image: philohsophy/transaction-pool:0.1.1
        name: transaction-pool
        env:
        - name: TRANSACTION_POOL_DB_HOST
          value: postgres
        - name: TRANSACTION_POOL_DB_PORT
          value: "5432"
        - name: TRANSACTION_POOL_DB_USERNAME
          value: transactions_user
        - name: TRANSACTION_POOL_DB_NAME
          value: transactions_db
        - name: TRANSACTION_POOL_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-pw
              key: password
        ports:
        - containerPort: 8010
          name: http-pool